apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs2
  labels:
    bucket: shared
spec:
  capacity:
    storage: 4T
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.192
    path: "/home/pi/nas"
